#!/bin/bash

dt=1
ofile=GPU_P.txt   #output file name

while :
do
        printf "Time: "  >> $ofile
        date +"%Y.%m.%d.%H.%M.%S.%3N" >> $ofile
        nvidia-smi -q -d MEMORY,POWER >> $ofile
        sleep $dt
done
